### PR TITLE
For sklearn compatibility 

### PR DESCRIPTION
**Pull request by jckkvs**
1.
It is a specification that the estimator of RuleFit (estimator) retains the estimator that has been learned once.
Again this can lead to bugs when using GridSearchCV or cross_val_predict. I'm not sure if my implementation of removing the estimator_ is best practice, but I think there should be an implementation that initializes the internal estimator in a similar way.
 
2.
The specification is that max_iter given as an argument is not reflected in self.max_iter. In this case, clone(estimator) may fail when using GridSearchCV and pipeline together.

### CODE REVIEW

**Review by chriswbartley — APPROVED** [review]
Nice work!

**Comment by chriswbartley** [comment]
Thanks jckkvs!

**Comment by PouyaREZ** [comment]
@chriswbartley, why did we delete `get_rules` function in this PR? I couldn't find any conflicts b/w the function and the main changes in this PR. Maybe I'm missing something?

**Comment by chriswbartley** [comment]
> @chriswbartley, why did we delete `get_rules` function in this PR? I couldn't find any conflicts b/w the function and the main changes in this PR. Maybe I'm missing something?

Oops, I missed that. Can you add a PR to restore get_rules? (or is there an easier way?)

**Comment by PouyaREZ** [comment]
Sure:
I have a local PR going, but I need push access to the repo. Can you give me access?

**Comment by chriswbartley** [comment]
If you make a pull request I can approve it (I'm no expert but that's how the original change was made)

**Pull request merged**
