### PR TITLE
Add Probability Prediction Method

### PR DESCRIPTION
**Pull request by ajshearer124**
Add wrapper method to predict probabilities via `predict_proba`, if that method exists in the sklearn class lscv.

### CODE REVIEW

**Comment by ajshearer124** [comment]
@christophM think this is a pretty straightforward addition, would like to see it merged in!

**Comment by christophM** [comment]
Hey, I just saw this. Thanks for opening this pull request!
Could you add a test as well? Then I think it would be ready to merge.

**Comment by ajshearer124** [comment]
Of course - added a separate script for some simple testing. Lmk what you think!

**Comment by christophM** [comment]
Thanks!

**Pull request merged**
